### ISSUE TITLE
Support for types extended_symbol and extended_asset

### ISSUE THREAD

**Issue by pbatmetal** [FACINGS/pyntelope#3]

**Comment by pbatmetal** [comment]
Could you please add support for types extended_asset and extended_symbol
If there is a way to including this in data without adding types, please do let me know
https://developers.eos.io/manuals/eosio.cdt/v1.4/structeosio_1_1extended__asset

**Comment by edinhodiluviano** [comment]
Hi @pbatmetal, we don't have plans for that yet. It would be really nice to have it!
If you submit a PR, we'll be happy to review.
Other option if you really need that in urgency, is to arrange a contribution for us to put in the resources for this feature. Feel free to DM me if you want so.
