### ISSUE TITLE
The handshake operation timed out

### ISSUE THREAD

**Issue by ASheng-0210** [FACINGS/pyntelope#4]
When I used the demo of <Use Send Message action> in https://pypi.org/project/pyntelope/
and replaced WaxTestnet with WaxMainNet.it response:socket.timeout: _ssl.c:1114: The handshake operation timed out.

**Comment by edinhodiluviano** [comment]
Hi @ASheng-0210 thanks for the feedback.
However we can't be be sure if this problem arise from the lib itself or from a connectivity problem between you and the node (most likely!).

When you use `pyntelope.net.WaxMainnet()` it tries to connect with `https://facings.waxpub.net` (you can check that `host` attribute in the `net` object).
If for any reason you can't connect with `https://facings.waxpub.net`, the library won't be able too. (to be sure if you can AND the server is up, you can just visit `https://facings.waxpub.net` on your browser and expect a 404 error)
If you just can't connect anyway, then the library can't solve that : /

**Comment by ASheng-0210** [comment]
您发送的邮件已收到，我会尽快处理，谢谢！ Your email has been received, I will deal with as soon as possible, thank you!

**Comment by edinhodiluviano** [comment]
I'll close this now. But feel free to comment again if you see you connection with the server fine, but the library's failing ; )
